"""Generate the verified ``latex_project/references.bib`` (P7-I04).

Only sources whose typed manifest record carries
``verification.status == "verified"`` are emitted. The generator is
pure: a typed :class:`SourceManifest` in, a deterministic BibLaTeX
string out. Output uses ``@online`` entries with the
``eprint``/``eprinttype=arxiv`` convention from
``docs/PRD_bibliography_and_citations.md`` §13.1 (style ``numeric``,
sorting ``none``, backend ``biber``).
"""

from __future__ import annotations

from .manifest import SourceManifest, SourceRecord

# BibLaTeX special characters that must be escaped inside braced
# string values to keep biber happy.
_LATEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


class BibGenError(RuntimeError):
    """Raised when bibliography emission fails."""


def _latex_escape(text: str) -> str:
    return "".join(_LATEX_ESCAPES.get(ch, ch) for ch in text)


def _author_field(authors: tuple[str, ...]) -> str:
    """Return the BibLaTeX-formatted ``author`` field value."""

    if not authors:
        raise BibGenError("bibliography entry requires at least one author")
    parts: list[str] = []
    for name in authors:
        if "," not in name:
            raise BibGenError(
                f"bibliography author must be in 'Family, Given' form; got {name!r}"
            )
        # Preserve the manifest's already-canonical 'Family, Given' form.
        parts.append(_latex_escape(name))
    return " and ".join(parts)


def render_entry(record: SourceRecord, *, primary_category: str | None = None) -> str:
    """Render one verified record as a single ``@online`` BibLaTeX entry."""

    if record.verification.status != "verified":
        raise BibGenError(
            f"record {record.citation_key!r} is not verified; refusing emission"
        )
    if record.arxiv_id is None or record.arxiv_url is None:
        raise BibGenError(
            f"record {record.citation_key!r} is missing arXiv identifiers"
        )
    lines: list[str] = [f"@online{{{record.citation_key},"]
    lines.append(f"  author       = {{{_author_field(record.authors)}}},")
    lines.append(f"  title        = {{{_latex_escape(record.title)}}},")
    lines.append(f"  date         = {{{record.year}}},")
    lines.append(f"  eprint       = {{{record.arxiv_id}}},")
    lines.append("  eprinttype   = {arxiv},")
    if primary_category:
        lines.append(f"  primaryclass = {{{_latex_escape(primary_category)}}},")
    if record.doi:
        lines.append(f"  doi          = {{{_latex_escape(record.doi)}}},")
    lines.append(f"  url          = {{{record.arxiv_url}}},")
    lines.append("}")
    return "\n".join(lines)


_HEADER = (
    "% =============================================================================\n"
    "% latex_project/references.bib\n"
    "%\n"
    "% Generated by P7-I04 from the verified source manifest. Do not edit by hand;\n"
    "% regenerate via:\n"
    "%   uv run python -m agentic_publishing_pipeline.bibliography.run_bibgen\n"
    "%\n"
    "% Only entries whose verification.status is 'verified' in\n"
    "% config/article_sources.yaml are emitted. The full per-source audit lives in\n"
    "% docs/SOURCES.md and results/run_logs/source_verification.json.\n"
    "%\n"
    "% Style fixed under docs/PRD_bibliography_and_citations.md §13.1:\n"
    "%   biblatex style=numeric, sorting=none, backend=biber.\n"
    "% =============================================================================\n"
    "\n"
)


def render_bib(
    manifest: SourceManifest,
    *,
    primary_categories: dict[str, str] | None = None,
) -> str:
    """Render the full ``references.bib`` body for the verified manifest."""

    verified = [r for r in manifest.records if r.verification.status == "verified"]
    if not verified:
        raise BibGenError("manifest contains no verified entries; refusing emission")
    seen_keys: set[str] = set()
    entries: list[str] = []
    primary_categories = primary_categories or {}
    for record in verified:
        if record.citation_key in seen_keys:
            raise BibGenError(f"duplicate citation_key in manifest: {record.citation_key!r}")
        seen_keys.add(record.citation_key)
        entries.append(
            render_entry(
                record,
                primary_category=primary_categories.get(record.arxiv_id or ""),
            )
        )
    return _HEADER + "\n\n".join(entries) + "\n"
